services:
  db:
    image: postgres:alpine3.22
    container_name: wallet-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: walletdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  app:
    build: .
    container_name: wallet-app
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/walletdb
      NODE_ENV: development
      PORT: 5000
    ports:
      - "5000:5000"
volumes:
  pgdata:
      